### PR TITLE
Don't analyze/run test target

### PR DESCRIPTION
**Pull request by jberkel**
Does not make sense for test targets.

### CODE REVIEW

**Comment by jberkel** [comment]
https://github.com/emaloney/CleanroomASL/pull/2

**Comment by emaloney** [comment]
Good catch! Thanks for the pull request!

**Comment by jberkel** [comment]
cool, can you merge the ASL one as well and update the submodule ref? Then I might finally be able to build my project on the CI :)

**Comment by emaloney** [comment]
Done. Please let me know how it goes and feel free to reach out if I can help.

**Comment by jberkel** [comment]
great, but the submodule ref from core->ASL still points to the old SHA => https://github.com/emaloney/CleanroomLogger/pull/8

**Comment by emaloney** [comment]
That's what I get for reading GitHub while standing on line at Chipotle ;)

I've issued a 1.2.1 release of CleanroomLogger which should refer to the correct CleanroomASL version.

**Comment by jberkel** [comment]
ok, can confirm that 1.2.1 now builds correctly via carthage on ship.io

**Comment by emaloney** [comment]
Nice! Thank you so much for going through the work of doing that.

**Pull request merged**
