### PR TITLE
Added support for unix time to default logger

### PR DESCRIPTION
**Pull request by jeeftor**
We have a need to have our times listed in epoch format in order to sync with internal data collection

### CODE REVIEW

**Comment by emaloney** [comment]
Hi, thanks for submitting this because it tipped me off to this feature being a desire. I was in the process of working on a 2.0 release, and I've added native support for UNIX timestamps and have made it easy to use them wherever you like.

If you wouldn't mind checking out the [refactoring](https://github.com/emaloney/CleanroomLogger/tree/refactoring) branch and giving it a try, I'm seeking feedback.

Using that branch, there are several different ways you could output timestamps in UNIX format.

The simplest way is to accept all other default settings but override the [TimestampStyle](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Enums/TimestampStyle.html) via [Log.enable()](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Structs/Log.html#/s:ZFV15CleanroomLogger3Log6enableFMS0_FT15minimumSeverityOS_11LogSeverity9debugModeSb16verboseDebugModeSb14timestampStyleGSqOS_14TimestampStyle_13severityStyleGSqOS_13SeverityStyle_12showCallSiteSb17showCallingThreadSb14suppressColorsSb7filtersGSaPS_9LogFilter___T_):

```swift
Log.enable(timestampStyle: .UNIX)
```

The new release will also contain additional `LogFormatter`s designed for specific tasks, such as:  [ReadableLogFileFormatter](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Classes/ReadableLogFileFormatter.html), [ParsableLogFileFormatter](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Classes/ParsableLogFileFormatter.html) and [XcodeLogFormatter](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Classes/XcodeLogFormatter.html). The constructors for each of these also accept a `TimestampStyle` parameter to allow you to select `.UNIX`.

Finally, you can assemble an entirely custom log file format quite easily now using the [FieldBasedLogFormatter](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Classes/FieldBasedLogFormatter.html). This class lets you mix-and-match [Fields](https://rawgit.com/emaloney/CleanroomLogger/refactoring/Documentation/API/Classes/FieldBasedLogFormatter/Field.html) to roll your own formatter.

Let's say you just wanted the following fields in your log output, each separated by a tab character:

- UNIX timestamp
- Numeric severity level
- Log message

You could build such a formatter with the code:

```swift
let formatter = FieldBasedLogFormatter(fields: [.Timestamp(.UNIX),
                                                .Delimiter(.Tab),
                                                .Severity(.Numeric),
                                                .Delimiter(.Tab),
                                                .Payload])
```

Finally, I should point out that there are breaking API changes on this branch, as noted in [this (possibly incomplete) draft here](https://github.com/emaloney/CleanroomLogger/blob/refactoring/BREAKING-CHANGES.md#200).

Please let me know whether this addresses your use-case.

Thanks,
E.

**Comment by emaloney** [comment]
(Updated comment above to account for in-dev changes.)

**Comment by emaloney** [comment]
Hi Jeef,

I've merged the refactored code shown above into the CleanroomLogger 2.0 release.

Since the feature listed above obviates the pull request, I will close it.

E.

**Comment by jeeftor** [comment]
thanks.

**Pull request closed without merging**
