### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by rosskimes**
Switch to Swift 2.0. Main changes are documentation and errors.

Would recommending making Swift 2.0 a separate branch until the GM seed.

### CODE REVIEW

**Comment by emaloney** [comment]
Thanks for the pull request, Ross. I will be making a separate swift-2.0 branch and will be doing some refactoring to use some of the new Swift goodness.

Until Xcode gives us a way to generate first-class, stand-alone API documentation, I'm going to leave the documentation as-is, however; I'm using [jazzy](https://github.com/realm/jazzy) to generate [the API documentation](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/index.html) which takes a slightly different format. Or perhaps jazzy will be updated to use Xcode's new format, in which case I'll update these docs then.

**Comment by emaloney** [comment]
FYI, the swift-2.0 branch is now available in this repo. It also automatically pulls in the swift-2.0 version of CleanroomASL.

**Comment by rosskimes** [comment]
👍

**Comment by emaloney** [comment]
Closing this pull request now that Swift 2.0 support is provided as of the 1.4.x release line.

**Pull request closed without merging**
